teleop:
  walk:
    type: topic
    message_type: geometry_msgs/Twist
    topic_name: cmd_vel
    deadman_buttons: [4]
    axis_mappings:
      -
        axis: 1
        target: linear.x
        scale: 0.5
      -
        axis: 0
        target: angular.z
        scale: 0.5
      -
        axis: 2
        target: linear.y
        scale: 0.3

  home:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: home
      reach_time:
        secs: 3
    buttons: [8, 1]

  hands_front:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: hands_front
      reach_time:
        secs: 3
    buttons: [8, 0]

  small_squat:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: small_squat
      reach_time:
        secs: 3
    buttons: [8, 2]
