teleop:
  sit:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: chair_sit
      reach_time:
        secs: 3
    buttons: [9, 1]
  stand:
    type: action
    action_name: play_motion
    action_goal:
      motion_name: stand_up
      reach_time:
        secs: 3
    buttons: [9, 3]
