play_motion:
  controllers: [right_arm_controller, left_arm_controller, left_leg_controller, right_leg_controller,
    torso_controller]
  motions:
    chair_sit:
      joints: [torso_2_joint, arm_left_1_joint, torso_1_joint, arm_left_4_joint, head_2_joint,
        leg_right_3_joint, arm_right_2_joint, arm_left_3_joint, head_1_joint, arm_right_3_joint,
        leg_left_5_joint, leg_right_4_joint, arm_right_4_joint, arm_right_1_joint,
        leg_left_4_joint, leg_right_5_joint, arm_left_2_joint, leg_left_3_joint]
      points:
      - positions: [0.3, 1.2, 0.0, 0.0, 0.25, -1.35, 0.3, -0.2, 0.0, -0.2, 0.0, 0.9,
          0.0, 1.2, 0.9, 0.0, 0.3, -1.35]
        velocities: [-0.1, -0.3, 0.0, 0.3, -0.1, 0.0, 0.0, -0.2, 0.0, -0.2, 0.0, 0.1,
          0.3, -0.3, 0.1, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.0, 0.2, 0.0, 1.0, 0.0, -1.1, 0.3, -1.0, 0.0, -1.0, 0.0, 1.2,
          1.0, 0.2, 1.2, 0.0, 0.3, -1.1]
        time_from_start: 4.0
    stand_up:
      joints: [torso_2_joint, arm_left_1_joint, torso_1_joint, arm_left_4_joint, head_2_joint,
        leg_right_3_joint, arm_right_2_joint, arm_left_3_joint, head_1_joint, arm_right_3_joint,
        leg_left_5_joint, leg_right_4_joint, arm_right_4_joint, arm_right_1_joint,
        leg_left_4_joint, leg_right_5_joint, arm_left_2_joint, leg_left_3_joint]
      points:
      - positions: [0.3, 1.2, 0.0, 0.0, 0.25, -1.35, 0.3, -0.2, 0.0, -0.2, 0.0, 0.9,
          0.0, 1.2, 0.9, 0.0, 0.3, -1.35]
        velocities: [-0.1, -0.3, 0.0, 0.3, -0.1, 0.0, 0.0, -0.2, 0.0, -0.2, 0.0, 0.1,
          0.3, -0.3, 0.1, 0.0, 0.0, 0.0]
        time_from_start: 0.0
      - positions: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
        time_from_start: 4.0
